export const AUDIT_ACTIONS = {
  RATE_OVERRIDE_BELOW_FLOOR: 'RATE_OVERRIDE_BELOW_FLOOR',
  FOLIO_LINE_VOIDED: 'FOLIO_LINE_VOIDED',
  RESERVATION_CANCELLED: 'RESERVATION_CANCELLED',
  RESERVATION_AMENDED: 'RESERVATION_AMENDED',
  DISCOUNT_APPLIED: 'DISCOUNT_APPLIED',
  ROOM_REASSIGNED: 'ROOM_REASSIGNED',
  ALERT_DISMISSED: 'ALERT_DISMISSED',
  COST_CONFIG_UPDATED: 'COST_CONFIG_UPDATED',
  CHECK_IN: 'CHECK_IN',
  CHECK_OUT: 'CHECK_OUT',
  NO_SHOW_MARKED: 'NO_SHOW_MARKED',
  GUEST_ID_REVEALED: 'GUEST_ID_REVEALED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  CREDIT_NOTE_ISSUED: 'CREDIT_NOTE_ISSUED',
  FOLIO_LINE_REFUNDED: 'FOLIO_LINE_REFUNDED',
  AUDIT_LOG_EXPORTED: 'AUDIT_LOG_EXPORTED',
  HOLD_EXPIRED: 'HOLD_EXPIRED',
  CHANNEL_CONNECTED: 'CHANNEL_CONNECTED',
  CHANNEL_DISCONNECTED: 'CHANNEL_DISCONNECTED',
  CHANNEL_PAUSED_TRIAL_EXPIRY: 'CHANNEL_PAUSED_TRIAL_EXPIRY',
  CONVERSION_ARC_CONFIG_UPDATED: 'CONVERSION_ARC_CONFIG_UPDATED',
  SUBSCRIPTION_STATUS_CHANGED: 'SUBSCRIPTION_STATUS_CHANGED',
  CATALOG_ITEM_CREATED: 'CATALOG_ITEM_CREATED',
  CATALOG_ITEM_UPDATED: 'CATALOG_ITEM_UPDATED',
  CATALOG_ITEM_DELETED: 'CATALOG_ITEM_DELETED',
  INVENTORY_RESTOCKED: 'INVENTORY_RESTOCKED',
  RECONCILIATION_DISCREPANCY_ACKNOWLEDGED: 'RECONCILIATION_DISCREPANCY_ACKNOWLEDGED',
  ROOM_BLOCKED: 'ROOM_BLOCKED',
  ROOM_BLOCK_LIFTED: 'ROOM_BLOCK_LIFTED',
  ROOM_BLOCK_EXPIRED: 'ROOM_BLOCK_EXPIRED',
  HOUSEKEEPING_STATUS_UPDATED: 'HOUSEKEEPING_STATUS_UPDATED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  RATE_OVERRIDE_BELOW_FLOOR: 'Rate Overridden Below Floor',
  FOLIO_LINE_VOIDED: 'Charge Voided',
  RESERVATION_CANCELLED: 'Reservation Cancelled',
  RESERVATION_AMENDED: 'Reservation Amended',
  DISCOUNT_APPLIED: 'Discount Applied',
  ROOM_REASSIGNED: 'Room Reassigned',
  ALERT_DISMISSED: 'Alert Dismissed',
  COST_CONFIG_UPDATED: 'Cost Config Updated',
  CHECK_IN: 'Guest Checked In',
  CHECK_OUT: 'Guest Checked Out',
  NO_SHOW_MARKED: 'No-Show Marked',
  GUEST_ID_REVEALED: 'Guest ID Revealed',
  AUTH_LOGOUT: 'Logged Out',
  AUTH_LOGIN_FAILED: 'Login Failed',
  INVOICE_ISSUED: 'Invoice Issued',
  CREDIT_NOTE_ISSUED: 'Credit Note Issued',
  FOLIO_LINE_REFUNDED: 'Refund Posted',
  AUDIT_LOG_EXPORTED: 'Audit Log Exported',
  HOLD_EXPIRED: 'Hold Expired',
  CHANNEL_CONNECTED: 'Channel Connected',
  CHANNEL_DISCONNECTED: 'Channel Disconnected',
  CHANNEL_PAUSED_TRIAL_EXPIRY: 'Channel Paused (Trial Expired)',
  CONVERSION_ARC_CONFIG_UPDATED: 'Conversion Arc Updated',
  SUBSCRIPTION_STATUS_CHANGED: 'Subscription Status Changed',
  CATALOG_ITEM_CREATED: 'Catalog Item Created',
  CATALOG_ITEM_UPDATED: 'Catalog Item Updated',
  CATALOG_ITEM_DELETED: 'Catalog Item Deleted',
  INVENTORY_RESTOCKED: 'Inventory Restocked',
  RECONCILIATION_DISCREPANCY_ACKNOWLEDGED: 'Reconciliation Discrepancy Acknowledged',
  ROOM_BLOCKED: 'Room Blocked',
  ROOM_BLOCK_LIFTED: 'Room Block Lifted',
  ROOM_BLOCK_EXPIRED: 'Room Block Expired',
  HOUSEKEEPING_STATUS_UPDATED: 'Housekeeping Status Updated',
};

export type AuditCategory = 'BOOKINGS' | 'BILLING' | 'SETTINGS';

export const AUDIT_CATEGORY_MAP: Record<AuditCategory, AuditAction[]> = {
  BOOKINGS: [
    'RESERVATION_CANCELLED',
    'RESERVATION_AMENDED',
    'CHECK_IN',
    'CHECK_OUT',
    'NO_SHOW_MARKED',
    'ROOM_REASSIGNED',
  ],
  BILLING: [
    'FOLIO_LINE_VOIDED',
    'DISCOUNT_APPLIED',
    'RATE_OVERRIDE_BELOW_FLOOR',
    'INVOICE_ISSUED',
    'CREDIT_NOTE_ISSUED',
    'FOLIO_LINE_REFUNDED',
  ],
  SETTINGS: [
    'COST_CONFIG_UPDATED',
    'CHANNEL_CONNECTED',
    'CHANNEL_DISCONNECTED',
    'CHANNEL_PAUSED_TRIAL_EXPIRY',
    'CONVERSION_ARC_CONFIG_UPDATED',
    'SUBSCRIPTION_STATUS_CHANGED',
    'CATALOG_ITEM_CREATED',
    'CATALOG_ITEM_UPDATED',
    'CATALOG_ITEM_DELETED',
    'INVENTORY_RESTOCKED',
    'ALERT_DISMISSED',
  ],
};

export function getAuditCategory(action: string): AuditCategory | 'OTHER' {
  for (const [category, actions] of Object.entries(AUDIT_CATEGORY_MAP)) {
    if ((actions as readonly string[]).includes(action)) return category as AuditCategory;
  }
  return 'OTHER';
}

export const AUDIT_ACTIONS_BY_CATEGORY: Record<AuditCategory | 'OTHER', readonly string[]> = {
  ...AUDIT_CATEGORY_MAP,
  OTHER: Object.values(AUDIT_ACTIONS).filter(
    (action) => getAuditCategory(action) === 'OTHER',
  ),
};
